export LANG=en_US.utf8
export LANGUAGE=en_US.utf8
export GOPRIVATE=github.bus.zalan.do

export PATH="$HOME/go/bin:$PATH:$HOME/.local/bin"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$PATH:/usr/local/go/bin:/home/droccia/.cargo/bin"
export PATH="$PATH:/home/droccia/.local/share/gem/ruby/2.7.0/bin"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$PATH:/home/diegoroccia/.local/bin"

export FPATH="$FPATH:$HOME/.config/zsh/completions"

autoload -U compinit && compinit

# bindkey -v
# export KEYTIMEOUT=1
# autoload -Uz edit-command-line
# zle -N edit-command-line
# bindkey -M vicmd V edit-command-line
#
# autoload -Uz surround
# zle -N delete-surround surround
# zle -N add-surround surround
# zle -N change-surround surround
# bindkey -M vicmd cs change-surround
# bindkey -M vicmd ds delete-surround
# bindkey -M vicmd ys add-surround
# bindkey -M visual S add-surround
#
# eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/config.json)"
#
