export LANG=en_US.utf8
export LANGUAGE=en_US.utf8
export GOPRIVATE=github.bus.zalan.do

export PATH="$HOME/go/bin:$PATH:$HOME/.local/bin"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$PATH:/usr/local/go/bin:/home/droccia/.cargo/bin"
export PATH="$PATH:/home/droccia/.local/share/gem/ruby/2.7.0/bin"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export PATH="$PATH:/home/diegoroccia/.local/bin"

export FPATH="$FPATH:$HOME/.config/zsh/completions"

autoload -U compinit && compinit
